# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Controller.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 270)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(260, 20, 141, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.labelState_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelState_2.setObjectName("labelState_2")
        self.gridLayout.addWidget(self.labelState_2, 1, 3, 1, 1)
        self.labelState_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelState_3.setObjectName("labelState_3")
        self.gridLayout.addWidget(self.labelState_3, 2, 3, 1, 1)
        self.labelState_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelState_1.setObjectName("labelState_1")
        self.gridLayout.addWidget(self.labelState_1, 0, 3, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 81, 192))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_label = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_label.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_label.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_label.setSpacing(6)
        self.verticalLayout_label.setObjectName("verticalLayout_label")
        self.label_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_1.setObjectName("label_1")
        self.verticalLayout_label.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_label.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_label.addWidget(self.label_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(130, 20, 121, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_button = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_button.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_button.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_button.setSpacing(6)
        self.verticalLayout_button.setObjectName("verticalLayout_button")
        self.SwitchBtn_1 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.SwitchBtn_1.setMinimumSize(QtCore.QSize(0, 40))
        self.SwitchBtn_1.setObjectName("SwitchBtn_1")
        self.verticalLayout_button.addWidget(self.SwitchBtn_1)
        self.SwitchBtn_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.SwitchBtn_2.setMinimumSize(QtCore.QSize(0, 40))
        self.SwitchBtn_2.setObjectName("SwitchBtn_2")
        self.verticalLayout_button.addWidget(self.SwitchBtn_2)
        self.SwitchBtn_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.SwitchBtn_3.setMinimumSize(QtCore.QSize(0, 40))
        self.SwitchBtn_3.setObjectName("SwitchBtn_3")
        self.verticalLayout_button.addWidget(self.SwitchBtn_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        # self.SwitchBtn_1.clicked.connect(self.labelState_1.clear)
        # self.SwitchBtn_2.clicked.connect(self.labelState_2.clear)
        # self.SwitchBtn_3.clicked.connect(self.labelState_3.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelState_2.setText(_translate("MainWindow", "OFF"))
        self.labelState_3.setText(_translate("MainWindow", "OFF"))
        self.labelState_1.setText(_translate("MainWindow", "OFF"))
        self.label_1.setText(_translate("MainWindow", "Valve 1"))
        self.label_2.setText(_translate("MainWindow", "Valve 2"))
        self.label_3.setText(_translate("MainWindow", "Valve 3"))
        self.SwitchBtn_1.setText(_translate("MainWindow", "Switch 1"))
        self.SwitchBtn_2.setText(_translate("MainWindow", "Switch 2"))
        self.SwitchBtn_3.setText(_translate("MainWindow", "Switch 3"))
