# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import res_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 270)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 160, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_C_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_C_0.setFont(font)
        self.label_C_0.setObjectName("label_C_0")
        self.gridLayout.addWidget(self.label_C_0, 0, 0, 1, 1)
        self.button_C_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_C_0.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo_switch/resource/switchoff_128px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/logo_switch/resource/switchon_128px.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_C_0.setIcon(icon)

        self.button_C_0.setCheckable(True)

        self.button_C_0.setIconSize(QtCore.QSize(32, 19))
        self.button_C_0.setObjectName("button_C_0")
        self.gridLayout.addWidget(self.button_C_0, 0, 1, 1, 1)
        self.label_C_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_C_1.setFont(font)
        self.label_C_1.setObjectName("label_C_1")
        self.gridLayout.addWidget(self.label_C_1, 1, 0, 1, 1)
        self.button_C_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_C_1.setText("")
        self.button_C_1.setIcon(icon)
        self.button_C_1.setIconSize(QtCore.QSize(32, 19))
        self.button_C_1.setObjectName("button_C_1")
        self.gridLayout.addWidget(self.button_C_1, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        self.menuControl = QtWidgets.QMenu(self.menubar)
        self.menuControl.setObjectName("menuControl")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAuto = QtWidgets.QAction(MainWindow)
        self.actionAuto.setObjectName("actionAuto")
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuControl.addAction(self.actionAuto)
        self.menuControl.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuControl.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        # self.button_C_0.clicked.connect(self.button_C_0.toggle)
        self.button_C_0.clicked.connect(self.button_C_0_change)
        # self.button_C_1.clicked.connect(self.button_C_1.toggle)
        self.button_C_1.clicked.connect(self.button_C_1_change)
        self.actionAbout.triggered.connect(self.actionAbout.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_C_0.setText(_translate("MainWindow", "LED 0"))
        self.label_C_1.setText(_translate("MainWindow", "LED 1"))
        self.menuControl.setTitle(_translate("MainWindow", "Control"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAuto.setText(_translate("MainWindow", "Auto"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

    def button_C_0_change(self):
        if(self.button_C_0.isChecked()):
            print("btnc0 is checked")
            # self.button_C_0.setCheckable(False)
        else:
            print("btnc0 not checked")
            # self.button_C_0.setCheckable(True)
    
    def button_C_1_change(self):
        if(self.button_C_0.isChecked()):
            print("btnc0 is checked")
        else:
            print("btnc0 not checked")
