# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 270)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 160, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_C_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_C_0.setFont(font)
        self.label_C_0.setObjectName("label_C_0")
        self.gridLayout.addWidget(self.label_C_0, 0, 0, 1, 1)
        self.button_C_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_C_0.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/switchoff_128px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("resource/switchon_128px.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_C_0.setIcon(icon)
        self.button_C_0.setIconSize(QtCore.QSize(32, 19))
        self.button_C_0.setObjectName("button_C_0")
        self.gridLayout.addWidget(self.button_C_0, 0, 1, 1, 1)
        self.label_C_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_C_1.setFont(font)
        self.label_C_1.setObjectName("label_C_1")
        self.gridLayout.addWidget(self.label_C_1, 1, 0, 1, 1)
        self.button_C_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_C_1.setText("")
        self.button_C_1.setIcon(icon)
        self.button_C_1.setIconSize(QtCore.QSize(32, 19))
        self.button_C_1.setObjectName("button_C_1")
        self.gridLayout.addWidget(self.button_C_1, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_C_0.setText(_translate("MainWindow", "LED 0"))
        self.label_C_1.setText(_translate("MainWindow", "LED 1"))
